# Generated by Django 5.2.5 on 2025-09-11 12:56

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TrainerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certifications', models.TextField(help_text='List of certifications and qualifications')),
                ('specializations', models.CharField(choices=[('personal_training', 'Personal Training'), ('mma', 'MMA Coaching'), ('boxing', 'Boxing'), ('strength', 'Strength & Conditioning'), ('yoga', 'Yoga'), ('pilates', 'Pilates'), ('nutrition', 'Nutrition Coaching'), ('physiotherapy', 'Physiotherapy')], max_length=100)),
                ('years_experience', models.IntegerField(default=0)),
                ('hourly_rate', models.DecimalField(decimal_places=2, max_digits=6)),
                ('is_accepting_clients', models.BooleanField(default=True)),
                ('max_clients', models.IntegerField(default=20)),
                ('bio', models.TextField(max_length=1000)),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='trainers/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(blank=True, max_length=17, validators=[django.core.validators.RegexValidator(regex='^\\+?1?\\d{9,15}$')])),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other'), ('P', 'Prefer not to say')], max_length=1)),
                ('emergency_contact_name', models.CharField(blank=True, max_length=100)),
                ('emergency_contact_phone', models.CharField(blank=True, max_length=17, validators=[django.core.validators.RegexValidator(regex='^\\+?1?\\d{9,15}$')])),
                ('fitness_level', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced'), ('athlete', 'Professional Athlete')], default='beginner', max_length=20)),
                ('primary_goal', models.CharField(blank=True, choices=[('weight_loss', 'Weight Loss'), ('muscle_gain', 'Muscle Gain'), ('fitness', 'General Fitness'), ('strength', 'Strength Training'), ('endurance', 'Endurance'), ('mma', 'MMA Training'), ('competition', 'Competition Prep')], max_length=20)),
                ('medical_conditions', models.TextField(blank=True, help_text='Any medical conditions or injuries')),
                ('preferred_training_time', models.CharField(blank=True, max_length=50)),
                ('newsletter_subscription', models.BooleanField(default=True)),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='profiles/')),
                ('bio', models.TextField(blank=True, max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
