# Generated by Django 5.2.5 on 2025-09-11 12:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('service_type', models.CharField(choices=[('personal_training', 'Personal Training'), ('group_class', 'Group Class'), ('mma_session', 'MMA Training'), ('consultation', 'Fitness Consultation'), ('assessment', 'Fitness Assessment')], max_length=20)),
                ('description', models.TextField()),
                ('duration_minutes', models.IntegerField(default=60)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('max_participants', models.IntegerField(default=1)),
                ('requires_membership', models.BooleanField(default=True)),
                ('minimum_fitness_level', models.CharField(blank=True, max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('status', models.CharField(choices=[('pending', 'Pending Confirmation'), ('confirmed', 'Confirmed'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('no_show', 'No Show')], default='pending', max_length=15)),
                ('participants', models.IntegerField(default=1)),
                ('special_requests', models.TextField(blank=True)),
                ('amount_paid', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('payment_status', models.CharField(default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('trainer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.trainerprofile')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookings.service')),
            ],
            options={
                'ordering': ['-date', '-start_time'],
            },
        ),
    ]
